server:
  port: 8083

spring:
  application:
    name: ranking-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rankingdb
springdoc:
  api-docs:
    path: /aulamatriz-doc
  show-actuator: true
  packages-to-scan: com.ms.ranking.controller
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
