spring:
  application:
    name: AUTH-SERVICE

admin-paths:
  paths:
    -
      uri: "/api/v2/user"
      method: "POST"
    -
      uri: "/api/v2/user"
      method: "GET"
durationToken:
  8
server:
  port:
    8086
eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

