
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_db
    username: root
    password: AulaMatriz123
    driver: com.mysql.cj.jdbc.Driver
  application:
    name: ms-user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /aulamatriz-doc
  show-actuator: false
  packages-to-scan: com.ms.user.controller
server:
  port: 8081
control:
  exception:
    business:
      business exception
    system:
      System Exception
# localhost:3307/user-db
# root
# AulaMatriz123
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka